/// CosmoRealtimeAPI — generated models + client for the published realtime
/// developer API (``sdks/cosmo-realtime/external-openapi.json``).
///
/// The OpenAPI generator build plugin produces ``Types.swift`` (all wire
/// schemas as Codable structs) and ``Client.swift`` (the REST operations)
/// from the spec symlinked at ``openapi.json``. The spec is regenerated by
/// ``backend/scripts/export_realtime_openapi.py`` — never hand-edit it.
///
/// This module is an implementation detail of the ``CosmoRealtime``
/// session API: consumers import ``CosmoRealtime`` and use the clean
/// typealiases it re-exports rather than importing this module directly.
